# Generated by Django 4.2.2 on 2023-07-03 05:55

from django.db import migrations

from django.contrib.auth import get_user_model

def create_user(apps,schema_editor):
    User = get_user_model()
    User.objects.create_superuser('admin','ryujin@gmail.com','Ryujin990202')
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user),
    ]
