# Generated by Django 4.2.2 on 2023-07-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id de usuario'),
        ),
    ]
