# Generated by Django 4.2.2 on 2023-07-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.PositiveIntegerField(verbose_name='Id de usuario'),
        ),
    ]
